#!/usr/bin/env python3
"""Generate app/src/main/cpp/case_fold.h — a simple (1:1) case-fold table.

For every BMP codepoint >= 0x80 whose Unicode lowercase mapping is a single,
different codepoint, emit a {codepoint, lowercase} pair. ASCII is folded
inline in C, so it is omitted here. This is *simple* case folding: 1:1 only,
so multi-character folds (e.g. SHARP S -> "ss", or LATIN CAPITAL I WITH DOT
ABOVE -> "i" + combining dot) are intentionally left out — they would break
the matcher's one-codepoint-per-cell position mapping. The lowercase-based
mapping matches simple case folding for the cased scripts that matter here
(Latin, Greek, Cyrillic, ...).

Usage:
    python3 scripts/gen-case-fold.py > app/src/main/cpp/case_fold.h
"""
import sys
import unicodedata

entries = []
for cp in range(0x80, 0x10000):
    lo = chr(cp).lower()
    if len(lo) == 1 and ord(lo) != cp:
        entries.append((cp, ord(lo)))
entries.sort()

out = []
out.append("/* Generated by scripts/gen-case-fold.py (Unicode %s). Do not edit. */"
           % unicodedata.unidata_version)
out.append("#ifndef CASE_FOLD_H")
out.append("#define CASE_FOLD_H")
out.append("")
out.append("#include <stdint.h>")
out.append("")
out.append("/* Sorted by [0]: a cased BMP codepoint -> its single lowercase fold.")
out.append(" * ASCII is folded inline; multi-character folds are omitted (simple")
out.append(" * folding), as is anything outside the BMP. */")
out.append("static const uint16_t CASE_FOLD[][2] = {")
line = "   "
for u, l in entries:
    tok = " {0x%04X, 0x%04X}," % (u, l)
    if len(line) + len(tok) > 79:
        out.append(line)
        line = "   "
    line += tok
if line.strip():
    out.append(line)
out.append("};")
out.append("")
out.append("#define CASE_FOLD_COUNT (sizeof(CASE_FOLD) / sizeof(CASE_FOLD[0]))")
out.append("")
out.append("#endif /* CASE_FOLD_H */")
sys.stdout.write("\n".join(out) + "\n")
