package sh.easycli.proot.ui;

import android.content.Context;
import android.content.SharedPreferences;
import android.view.KeyEvent;

import org.json.JSONArray;
import org.json.JSONException;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.Collections;
import java.util.HashSet;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Locale;
import java.util.Set;

import sh.easycli.proot.R;
import sh.easycli.proot.term.TerminalNative;

/**
 * The source of truth for the extra-keys toolbar layout: the built-in key
 * {@linkplain #catalog catalog} plus the user's ordered list of enabled key ids.
 *
 * Same approach as {@link ThemeStore}: the order is persisted in its own
 * {@link SharedPreferences} file as a JSON array of ids, so it survives process
 * death. An id is either a catalog key (e.g. {@code "esc"}) or {@code "lit:"} +
 * an arbitrary literal for a user-defined text key.
 *
 * The catalog is intentionally limited to keys the native {@code map_keycode}
 * (terminal_jni.c) actually encodes — offering a key that produces nothing would
 * be a dead button.
 */
public final class ExtraKeysConfig {

    private static final String FILE = "extrakeys";
    private static final String KEY_ORDER = "order";

    /** Prefix marking a user-defined literal text key; the rest is the text. */
    static final String CUSTOM_PREFIX = "lit:";

    /**
     * Prefix marking a modifier combo key. The id is
     * {@code combo:<mods>:<base>}, where {@code <mods>} is a subset of
     * {@code "CAS"} (Ctrl/Alt/Shift, in that order) and {@code <base>} is either
     * a catalog special-key id (e.g. {@code "right"}) or a single printable char.
     */
    static final String COMBO_PREFIX = "combo:";

    /**
     * The default toolbar — the original hardcoded order. Kept byte-for-byte so
     * a fresh install (and the UI tests asserting ESC/CTRL/"/"/"─") behave as
     * before.
     */
    static final List<String> DEFAULT_IDS = Collections.unmodifiableList(Arrays.asList(
            "esc", "ctrl", "alt", "tab", "up", "down", "left", "right",
            "home", "end", "pgup", "pgdn", "dash", "slash", "pipe"));

    /**
     * The most rows the toolbar will ever show. Each row eats vertical space
     * above the keyboard, so this stays small; the editor caps additions here.
     */
    static final int MAX_ROWS = 3;

    /**
     * The default layout: the legacy {@link #DEFAULT_IDS} as a single row, so a
     * fresh install and {@link #reset()} look exactly as before the toolbar
     * gained rows.
     */
    static final List<List<String>> DEFAULT_ROWS =
            Collections.singletonList(DEFAULT_IDS);

    /**
     * Modifier-combo presets offered in the "Add keys" palette (none enabled by
     * default, so the stock toolbar is unchanged). Each is a canonical
     * {@link #COMBO_PREFIX} id; the matching label is generated by
     * {@link #buildCombo}. Common signals and readline edits, then a couple of
     * modified special keys.
     */
    static final List<String> COMBO_PRESET_IDS = Collections.unmodifiableList(Arrays.asList(
            "combo:C:c", "combo:C:d", "combo:C:z", "combo:C:l", "combo:C:r",
            "combo:C:a", "combo:C:e", "combo:C:u", "combo:C:k", "combo:C:w",
            "combo:C:\\", "combo:S:tab", "combo:C:left", "combo:C:right"));

    private final SharedPreferences prefs;

    public ExtraKeysConfig(Context context) {
        prefs = context.getApplicationContext()
                .getSharedPreferences(FILE, Context.MODE_PRIVATE);
    }

    /**
     * Every built-in key, keyed by id, in catalog (display) order: the plain
     * {@linkplain #baseCatalog base keys} followed by the modifier-combo presets.
     */
    static LinkedHashMap<String, ExtraKey> catalog(Context c) {
        LinkedHashMap<String, ExtraKey> m = baseCatalog(c);
        for (String id : COMBO_PRESET_IDS) {
            ExtraKey k = resolveCombo(c, id);
            if (k != null) put(m, k);
        }
        return m;
    }

    /**
     * The plain built-in keys (no combos), keyed by id, in catalog order. Labels
     * come from resources where one exists; F-keys and punctuation are inlined
     * since their glyphs are universal. Kept separate from {@link #catalog} so
     * {@link #buildCombo} can resolve a combo's base key without recursing.
     */
    private static LinkedHashMap<String, ExtraKey> baseCatalog(Context c) {
        LinkedHashMap<String, ExtraKey> m = new LinkedHashMap<>();
        // Sticky modifiers.
        put(m, ExtraKey.modifier("ctrl", c.getString(R.string.key_ctrl), TerminalNative.MOD_CTRL));
        put(m, ExtraKey.modifier("alt", c.getString(R.string.key_alt), TerminalNative.MOD_ALT));
        // Non-printable keys (sent through the VT encoder).
        put(m, ExtraKey.key("esc", c.getString(R.string.key_esc), KeyEvent.KEYCODE_ESCAPE));
        put(m, ExtraKey.key("tab", c.getString(R.string.key_tab), KeyEvent.KEYCODE_TAB));
        put(m, ExtraKey.key("enter", c.getString(R.string.key_enter), KeyEvent.KEYCODE_ENTER));
        put(m, ExtraKey.key("bksp", c.getString(R.string.key_bksp), KeyEvent.KEYCODE_DEL));
        put(m, ExtraKey.key("del", c.getString(R.string.key_del), KeyEvent.KEYCODE_FORWARD_DEL));
        put(m, ExtraKey.key("ins", c.getString(R.string.key_ins), KeyEvent.KEYCODE_INSERT));
        put(m, ExtraKey.key("up", c.getString(R.string.key_up), KeyEvent.KEYCODE_DPAD_UP));
        put(m, ExtraKey.key("down", c.getString(R.string.key_down), KeyEvent.KEYCODE_DPAD_DOWN));
        put(m, ExtraKey.key("left", c.getString(R.string.key_left), KeyEvent.KEYCODE_DPAD_LEFT));
        put(m, ExtraKey.key("right", c.getString(R.string.key_right), KeyEvent.KEYCODE_DPAD_RIGHT));
        put(m, ExtraKey.key("home", c.getString(R.string.key_home), KeyEvent.KEYCODE_MOVE_HOME));
        put(m, ExtraKey.key("end", c.getString(R.string.key_end), KeyEvent.KEYCODE_MOVE_END));
        put(m, ExtraKey.key("pgup", c.getString(R.string.key_pgup), KeyEvent.KEYCODE_PAGE_UP));
        put(m, ExtraKey.key("pgdn", c.getString(R.string.key_pgdn), KeyEvent.KEYCODE_PAGE_DOWN));
        for (int i = 0; i < 12; i++) {
            put(m, ExtraKey.key("f" + (i + 1), "F" + (i + 1), KeyEvent.KEYCODE_F1 + i));
        }
        // Literal text keys. "dash" shows "─" but sends "-" (legacy label).
        put(m, ExtraKey.text("dash", c.getString(R.string.key_dash), "-"));
        put(m, ExtraKey.text("slash", c.getString(R.string.key_slash), "/"));
        put(m, ExtraKey.text("pipe", c.getString(R.string.key_pipe), "|"));
        for (String s : new String[]{"~", "`", "*", "=", "+", "#", ":", ";", "<", ">", "&", "?"}) {
            put(m, ExtraKey.text(literalId(s), s, s));
        }
        return m;
    }

    private static void put(LinkedHashMap<String, ExtraKey> m, ExtraKey k) {
        m.put(k.id, k);
    }

    /** The persistence id for a custom/literal text key. */
    static String literalId(String text) {
        return CUSTOM_PREFIX + text;
    }

    /** The canonical id for a modifier combo over {@code base} (special-key id or char). */
    static String comboId(int mods, String base) {
        return COMBO_PREFIX + modLetters(mods) + ":" + base;
    }

    /** Resolves an id to its key (catalog entry, custom literal, or combo); null if unknown. */
    static ExtraKey resolve(Context c, String id) {
        ExtraKey k = catalog(c).get(id);
        if (k != null) return k;
        if (id.startsWith(COMBO_PREFIX)) return resolveCombo(c, id);
        if (id.startsWith(CUSTOM_PREFIX)) {
            String t = id.substring(CUSTOM_PREFIX.length());
            if (!t.isEmpty()) {
                String label = t.replaceAll("\n+$", "");
                if (label.isEmpty()) label = "↵";
                return ExtraKey.text(id, label, t);
            }
        }
        return null;
    }

    /** Parses a {@code combo:<mods>:<base>} id and builds it; null if malformed. */
    private static ExtraKey resolveCombo(Context c, String id) {
        String rest = id.substring(COMBO_PREFIX.length());
        int sep = rest.indexOf(':');
        if (sep < 0) return null;
        int mods = parseMods(rest.substring(0, sep));
        String base = rest.substring(sep + 1);
        return buildCombo(c, id, mods, base);
    }

    /**
     * Builds a combo key for {@code base}: a non-printable special-key id maps to
     * a mode-aware {@link ExtraKey#comboKey}; a single printable char maps to a
     * {@link ExtraKey#comboText}. Returns null when {@code base} is neither.
     */
    private static ExtraKey buildCombo(Context c, String id, int mods, String base) {
        if (mods == 0 || base.isEmpty()) return null;
        ExtraKey special = baseCatalog(c).get(base);
        if (special != null && special.kind == ExtraKey.Kind.KEY) {
            return ExtraKey.comboKey(id, modPrefix(c, mods) + " " + special.label,
                    special.keyCode, mods);
        }
        if (base.codePointCount(0, base.length()) == 1) {
            return ExtraKey.comboText(id, modPrefix(c, mods) + " " + displayBase(base),
                    base, mods);
        }
        return null;
    }

    /** Label-friendly form of a single-char base: letters upper-cased ("CTRL C"). */
    private static String displayBase(String base) {
        return base.length() == 1 ? base.toUpperCase(Locale.ROOT) : base;
    }

    /** Mods bitmask → canonical letters, fixed Ctrl/Alt/Shift order ("CA"). */
    private static String modLetters(int mods) {
        StringBuilder sb = new StringBuilder(3);
        if ((mods & TerminalNative.MOD_CTRL) != 0) sb.append('C');
        if ((mods & TerminalNative.MOD_ALT) != 0) sb.append('A');
        if ((mods & TerminalNative.MOD_SHIFT) != 0) sb.append('S');
        return sb.toString();
    }

    /** Inverse of {@link #modLetters}; ignores unknown letters. */
    private static int parseMods(String letters) {
        int mods = 0;
        if (letters.indexOf('C') >= 0) mods |= TerminalNative.MOD_CTRL;
        if (letters.indexOf('A') >= 0) mods |= TerminalNative.MOD_ALT;
        if (letters.indexOf('S') >= 0) mods |= TerminalNative.MOD_SHIFT;
        return mods;
    }

    /**
     * Text prefix for a combo label, modifiers spelled out and joined by "-" in
     * fixed Ctrl/Alt/Shift order: "CTRL", "CTRL-ALT", "SHIFT", … Always non-empty
     * for a valid combo ({@link #buildCombo} rejects {@code mods == 0}). Labels
     * come from the same resources as the standalone modifier buttons.
     */
    private static String modPrefix(Context c, int mods) {
        StringBuilder sb = new StringBuilder();
        if ((mods & TerminalNative.MOD_CTRL) != 0) appendMod(sb, c.getString(R.string.key_ctrl));
        if ((mods & TerminalNative.MOD_ALT) != 0) appendMod(sb, c.getString(R.string.key_alt));
        if ((mods & TerminalNative.MOD_SHIFT) != 0) appendMod(sb, c.getString(R.string.key_shift));
        return sb.toString();
    }

    private static void appendMod(StringBuilder sb, String label) {
        if (sb.length() > 0) sb.append('-');
        sb.append(label);
    }

    /**
     * The persisted toolbar layout as rows of ids, or {@link #DEFAULT_ROWS} if
     * never set. Reads both the current nested format (a JSON array of arrays)
     * and the legacy flat format (a JSON array of ids → a single row), so old
     * saved configs keep working. Empty rows are dropped and the result is
     * capped at {@link #MAX_ROWS}.
     */
    public List<List<String>> rows() {
        String raw = prefs.getString(KEY_ORDER, null);
        if (raw == null) return copyRows(DEFAULT_ROWS);
        try {
            JSONArray arr = new JSONArray(raw);
            List<List<String>> out = new ArrayList<>();
            if (arr.length() > 0 && arr.opt(0) instanceof JSONArray) {
                for (int i = 0; i < arr.length() && out.size() < MAX_ROWS; i++) {
                    JSONArray r = arr.optJSONArray(i);
                    if (r == null) continue;
                    List<String> row = new ArrayList<>(r.length());
                    for (int j = 0; j < r.length(); j++) row.add(r.getString(j));
                    if (!row.isEmpty()) out.add(row);
                }
            } else {  // legacy flat format: one row of ids
                List<String> row = new ArrayList<>(arr.length());
                for (int i = 0; i < arr.length(); i++) row.add(arr.getString(i));
                if (!row.isEmpty()) out.add(row);
            }
            return out;
        } catch (JSONException malformed) {
            return copyRows(DEFAULT_ROWS);
        }
    }

    /** Persists the layout as a JSON array of arrays, dropping empty rows and capping at {@link #MAX_ROWS}. */
    public void setRows(List<List<String>> rows) {
        JSONArray arr = new JSONArray();
        for (List<String> row : rows) {
            if (row.isEmpty() || arr.length() >= MAX_ROWS) continue;
            JSONArray r = new JSONArray();
            for (String id : row) r.put(id);
            arr.put(r);
        }
        prefs.edit().putString(KEY_ORDER, arr.toString()).apply();
    }

    /**
     * The persisted enabled ids flattened across rows, or the defaults if never
     * set. Kept for callers that only need the flat set (e.g. the settings key
     * count); the toolbar itself uses {@link #rows()} / {@link #enabledRows}.
     */
    public List<String> order() {
        List<String> out = new ArrayList<>();
        for (List<String> row : rows()) out.addAll(row);
        return out;
    }

    public void setOrder(List<String> ids) {
        JSONArray arr = new JSONArray();
        for (String id : ids) arr.put(id);
        prefs.edit().putString(KEY_ORDER, arr.toString()).apply();
    }

    /** Drops the saved layout so {@link #rows()} returns the defaults again. */
    public void reset() {
        prefs.edit().remove(KEY_ORDER).apply();
    }

    /** The enabled keys per row, resolving ids and dropping any that no longer resolve (and empty rows). */
    public List<List<ExtraKey>> enabledRows(Context c) {
        List<List<ExtraKey>> out = new ArrayList<>();
        for (List<String> row : rows()) {
            List<ExtraKey> resolved = new ArrayList<>(row.size());
            for (String id : row) {
                ExtraKey k = resolve(c, id);
                if (k != null) resolved.add(k);
            }
            if (!resolved.isEmpty()) out.add(resolved);
        }
        return out;
    }

    /** The enabled keys flattened across rows, skipping any id that no longer resolves. */
    public List<ExtraKey> enabledKeys(Context c) {
        List<ExtraKey> out = new ArrayList<>();
        for (List<ExtraKey> row : enabledRows(c)) out.addAll(row);
        return out;
    }

    private static List<List<String>> copyRows(List<List<String>> src) {
        List<List<String>> out = new ArrayList<>(src.size());
        for (List<String> row : src) out.add(new ArrayList<>(row));
        return out;
    }

    /** Catalog keys not currently enabled — the "add" palette. */
    public List<ExtraKey> availableBuiltins(Context c) {
        Set<String> enabled = new HashSet<>(order());
        List<ExtraKey> out = new ArrayList<>();
        for (ExtraKey k : catalog(c).values()) {
            if (!enabled.contains(k.id)) out.add(k);
        }
        return out;
    }
}
